About us page
sandboxnu/good-dog-licensing pull request #20
Opened 2024-11-07 03:43 UTC by tracyyh

## Description

## Motivation and Context

Closes [story]()

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] CI/CD changes (changing github actions or deployment scripts)
- [ ] Database migration
- [ ] Environment variable change
- [ ] New package(s)
- [ ] New dependencies
- [ ] Global style changes
- [ ] Project configuration

## Checklist:

- [ ] I verified my changes work in the local environment
- [ ] I verified my changes work in the preview environment
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

## How has this been tested?

2024-11-12 20:01 UTC, owens1127 requested changes

2024-11-14 00:32 UTC, ispapa commented on apps/web/app/(pages)/about/page.tsx
> +              Connecting creativity
```suggestion
              Connecting Creatives
```

2024-11-14 03:17 UTC, sanjana-singhania commented on apps/web/app/(pages)/about/page.tsx
> +          }}
I think I got most of these? @tracyyh would you mind double checking (esp for the media musician maker divs)

2024-11-14 21:33 UTC, tracyyh commented
@sanjana-singhania changed a couple of minor styling things, other than that, LGTM 🔥 Do you mind taking a look at the conflicts LMFAO i dont remember how you did it last time

2024-11-15 00:16 UTC, owens1127 approved these changes

2024-11-15 00:17 UTC, merged